[build]
  publish = "."
  command = ""

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

[[headers]]
  for = "/assets/media/*.mp4"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/assets/books/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
